arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart # Keep original name for now
output-dir: lib/generated/l10n # Specify output directory
synthetic-package: false # Disable synthetic package generation
