// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5s5IMgglTd7Mnm66A9XMukqc93jwTXKY',
    appId: '1:391813617115:web:6d33b5f4f4518eb77543fe',
    messagingSenderId: '391813617115',
    projectId: 'quit-smart-app',
    authDomain: 'quit-smart-app.firebaseapp.com',
    storageBucket: 'quit-smart-app.firebasestorage.app',
    measurementId: 'G-MSNRPMM93Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZtOVjoYH3qR-FMDinRZSQ6cs_wMchsCU',
    appId: '1:391813617115:android:78620d1875655ec97543fe',
    messagingSenderId: '391813617115',
    projectId: 'quit-smart-app',
    storageBucket: 'quit-smart-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-yjDIbLC0BVYVKXrMGIYFIR-g3NbB-ic',
    appId: '1:391813617115:ios:edf8b4603d668e227543fe',
    messagingSenderId: '391813617115',
    projectId: 'quit-smart-app',
    storageBucket: 'quit-smart-app.firebasestorage.app',
    iosBundleId: 'com.example.quitSmartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-yjDIbLC0BVYVKXrMGIYFIR-g3NbB-ic',
    appId: '1:391813617115:ios:edf8b4603d668e227543fe',
    messagingSenderId: '391813617115',
    projectId: 'quit-smart-app',
    storageBucket: 'quit-smart-app.firebasestorage.app',
    iosBundleId: 'com.example.quitSmartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5s5IMgglTd7Mnm66A9XMukqc93jwTXKY',
    appId: '1:391813617115:web:a8fdb8a4b3157d667543fe',
    messagingSenderId: '391813617115',
    projectId: 'quit-smart-app',
    authDomain: 'quit-smart-app.firebaseapp.com',
    storageBucket: 'quit-smart-app.firebasestorage.app',
    measurementId: 'G-M3DG2WKVBV',
  );
}
